eureka:
    client:
        fetchRegistry: true
        registerWithEureka: false
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: false
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        gateway:
            enabled: true

server:
    port: 9000
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: notification
                  uri: lb://notification-service
                  predicates:
                      - Path=/alert/**
                  filters:
                      - RewritePath=/alert/(?<path>.*), /$\{path}
                - id: inventory
                  uri: lb://inventory-service
                  predicates:
                      - Path=/in/**
                  filters:
                      - RewritePath=/in/(?<path>.*), /$\{path}
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true

